"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oup%-*&wir2763-vce1e--0v4zw*fni-6do8^a$34t8iuha9!s'
AWS_ACCESS_KEY_ID = 'AKIAX72C3EPOIP27KWYD'
AWS_SECRET_ACCESS_KEY = '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'
DEBUG = True

ALLOWED_HOSTS = ['*']

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'iletisim@rubasoft.com'
EMAIL_HOST_PASSWORD = 'ewqevnmewczmrwst'
EMAIL_ADMIN = 'iletisim@rubasoft.com'
DEFAULT_FROM_EMAIL = 'IRSA |  <iletisim@rubasoft.com>'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# EMAIL_USE_SSL =False
# EMAIL_USE_STARTTLS = True
# Application definition


# Application definition

DJANGO_APPS = [
    # 'admin_menu',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
THIRD_PARTY_APPS = [
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django.contrib.sites',
    'crispy_forms',
    'ckeditor',
    'ckeditor_uploader',
    'translations',
    'rosetta',
    # "django_measurement",
    # "django_prices",
    "mptt",
    # "django_filters",
    'storages',
    'collectfast',
]

LOCAL_APPS = [
    'apps.main',
    'apps.product',
    'apps.accounts',
    'apps.checkout',
    'apps.order',
    'apps.basket',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.main.views.categories_menu_list',
                'apps.main.views.site_social_links',
                'apps.main.views.site_settings',
                'apps.main.views.view_cart',
                'apps.basket.context_processors.basket',

            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd844ljqvs8b52t',
        'USER': 'vhtutnslewnpsr',
        'PASSWORD': '905897c2b1d96c002a33aa91db36c73cda1854c77b50c5b637ee5776a7cd39a5',
        'HOST': 'ec2-34-233-115-14.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Captcha Fields

import random


def captcha_challenge():
    ret = u''
    for i in range(4):
        ret += str(random.randint(0, 9))
    return ret, ret


CAPTCHA_IMAGE_SIZE = (130, 60)
CAPTCHA_FONT_SIZE = 36
CAPTCHA_CHALLENGE_FUNCT = captcha_challenge

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'tr-Tr'
LANGUAGES = [
    ('tr', _('Turkish')),
    ('en', _('English')),

]
USE_TZ = True
TIME_ZONE = 'Europe/Istanbul'
# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/


USE_I18N = True

USE_L10N = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

AWS_STORAGE_BUCKET_NAME = 'test-batiozdmr'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

AWS_S3_CUSTOM_DOMAIN = 'test-batiozdmr.s3.eu-central-1.amazonaws.com'
S3_URL = 'https://%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATIC_URL = S3_URL + '/static/'

MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')
MEDIA_URL = S3_URL + '/media/'

DEFAULT_FILE_STORAGE = 'shop.s3_settings.MediaS3BotoStorage'
STATICFILES_STORAGE = 'shop.s3_settings.StaticS3BotoStorage'
THUMBNAIL_DEFAULT_STORAGE = 'shop.s3_settings.ThumbS3BotoStorage'
COLLECTFAST_STRATEGY = "collectfast.strategies.boto3.Boto3Strategy"
COLLECTFAST_THREADS = 10
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend"
)

LOGIN_REDIRECT_URL = '/tr/accounts/'
LOGOUT_REDIRECT_URL = '/'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
SITE_ID = 1

# Basket session ID
BASKET_SESSION_ID = "basket"

PERMISSION_DENIED_PAGE_URL = '/403'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_JQUERY_URL = os.path.join(STATIC_URL, 'assets/plugins/jquery.min.js')
MODELTRANSLATION_DEFAULT_LANGUAGE = 'tr-Tr'
DATE_INPUT_FORMATS = ['%d/%m/%Y']
LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
CKEDITOR_ALLOW_NONIMAGE_FILES = False

LOGIN_URL = '/account/login/'

# phonenumber_field
PHONENUMBER_DEFAULT_REGION = "TR"
ADMIN_LOGO = 'logo.png'
ADMIN_STYLE = {
    'background': 'white',
    'primary-color': '#205280',
    'primary-text': '#d6d5d2',
    'secondary-color': '#3B75AD',
    'secondary-text': 'white',
    'tertiary-color': '#F2F9FC',
    'tertiary-text': 'black',
    'breadcrumb-color': 'whitesmoke',
    'breadcrumb-text': 'black',
    'focus-color': '#eaeaea',
    'focus-text': '#666',
    'primary-button': '#26904A',
    'primary-button-text': ' white',
    'secondary-button': '#999',
    'secondary-button-text': 'white',
    'link-color': '#333',
    'link-color-hover': 'lighten($link-color, 20%)',
    'logo-width': 'auto',
    'logo-height': '35px'
}
