# Generated by Django 3.0.8 on 2022-12-01 16:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('order_id', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Sipariş No')),
                ('cargo_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kargo Takip No')),
                ('payment_status', models.BooleanField(default=False, null=True, verbose_name='Ödeme Durumu')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Toplam Ödeme')),
                ('billing_address_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Fatura Adresi')),
                ('shipping_address_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Teslimat Adresi')),
                ('return_bank', models.TextField(blank=True, null=True, verbose_name='Banka Geri Dönüşü')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sipariş Sahibi')),
                ('cargo_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.CargoCompany', verbose_name='Kargo Firması')),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CouponCodeList', to='checkout.CouponCodeList', verbose_name='Kupon Kodu')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.OrderStatus', verbose_name='Sipariş Durumu')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Sipariş Listesi',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Fiyat')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('explanation', models.CharField(blank=True, default='', max_length=50, verbose_name='Sipariş Açıklaması')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.Attributes', verbose_name='Ürün Seçenek')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.Order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Ürünü',
                'verbose_name_plural': 'Sipariş Ürünleri',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
    ]
