# Generated by Django 3.0.8 on 2022-12-01 16:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('header_text', models.CharField(blank=True, max_length=400, verbose_name='Firma Adı')),
                ('header_sort_text', models.CharField(blank=True, max_length=400, verbose_name='Başlık Metin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Firma Açıklaması')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='Head Tag')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='Footer Metni')),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='images/contents/', verbose_name='Firma Logosu')),
                ('company_logo_footer', models.FileField(blank=True, null=True, upload_to='images/contents/', verbose_name='Firma Logosu Footer')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Etiketler')),
                ('bank_logo', models.FileField(blank=True, null=True, upload_to='images/contents/', verbose_name='Banka Logosu')),
                ('bank_name', models.TextField(blank=True, null=True, verbose_name='Banka Adı')),
                ('bank_iban', models.TextField(blank=True, null=True, verbose_name='IBAN')),
                ('bank_account_name', models.TextField(blank=True, null=True, verbose_name='Hesap Unvanı')),
                ('bank_info_message', models.TextField(blank=True, null=True, verbose_name='Ödeme Uyarı Metni')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Posta')),
                ('company_about', ckeditor.fields.RichTextField(blank=True, verbose_name='Hakkımızda')),
                ('company_legal', ckeditor.fields.RichTextField(blank=True, verbose_name='Gizlilik Politikası')),
                ('company_faq', ckeditor.fields.RichTextField(blank=True, verbose_name='Sıkça Sorulan Sorular')),
                ('company_contact', ckeditor.fields.RichTextField(blank=True, verbose_name='İletişim')),
                ('company_legal_2', ckeditor.fields.RichTextField(blank=True, verbose_name='Teslimat ve İade')),
                ('company_legal_3', ckeditor.fields.RichTextField(blank=True, verbose_name='Mesafeli Satış Sözleşmesi')),
                ('company_legal_4', ckeditor.fields.RichTextField(blank=True, verbose_name='Kullanım Koşullarımız')),
                ('kvkk', ckeditor.fields.RichTextField(blank=True, verbose_name='Kişisel Verileri Koruma Kanunu (KVKK)')),
                ('footer_banner', models.FileField(blank=True, null=True, upload_to='images/contents/', verbose_name='Footer Banner')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.Site', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları Listesi',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
    ]
